name: azure-functions-otel

services:
  redis:
    image: redis:${REDIS_VERSION:-7.4-alpine@sha256:858f009f9709ce576febc734aa78b8f6d624b82571f9ddb6bda4377c833b3499}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:${AZURITE_VERSION:-3.37.0@sha256:830430c1da1a2d537e08f3e6764dd1f5ae00cf0346bcaf625b968ec3f0971fd5}
    ports:
      - "10000:10000"
    volumes:
      - azurite-data:/data
    restart: unless-stopped

  collector:
    image: otel/opentelemetry-collector-contrib:${COLLECTOR_VERSION:-0.161.0@sha256:fd328de2552466ad78385e1b1289c3f2402b1c45f265b252aab1955b42845ac1}
    command: [ "--config=/conf/collector-config.yaml" ]
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - TENANT_ID=${TENANT_ID}
      - TRACES_ENDPOINT=${TRACES_ENDPOINT}
      - LOGS_ENDPOINT=${LOGS_ENDPOINT}
      - METRICS_ENDPOINT=${METRICS_ENDPOINT}
    ports:
      - "4317:4317"
    volumes:
      - ./config/collector.yaml:/conf/collector-config.yaml:ro
    restart: unless-stopped

volumes:
  redis-data:
  azurite-data:
