output "application_insights_name" {
  description = "Name of the Application Insights component."
  value       = azapi_resource.application_insights.name
}

output "application_insights_resource_id" {
  description = "Resource ID of the Application Insights component."
  value       = azapi_resource.application_insights.id
}

output "application_insights_instrumentation_key" {
  description = "Instrumentation key of the Application Insights component."
  value       = data.azapi_resource.application_insights.output.instrumentation_key
  sensitive   = true
}

output "log_analytics_workspace_resource_id" {
  description = "Resource ID of the Log Analytics workspace."
  value       = azurerm_log_analytics_workspace.this.id
}

output "azure_monitor_workspace_resource_id" {
  description = "Resource ID of the Azure Monitor workspace."
  value       = azurerm_monitor_workspace.this.id
}

output "trace_ingestion_endpoint" {
  description = "Application Insights OTLP trace ingestion endpoint."
  value       = data.azapi_resource.application_insights.output.trace_ingestion_endpoint
}

output "log_ingestion_endpoint" {
  description = "Application Insights OTLP log ingestion endpoint."
  value       = data.azapi_resource.application_insights.output.log_ingestion_endpoint
}

output "metrics_ingestion_endpoint" {
  description = "Application Insights OTLP metrics ingestion endpoint."
  value       = data.azapi_resource.application_insights.output.metrics_ingestion_endpoint
}

output "data_collection_rule_resource_id" {
  description = "Resource ID of the data collection rule generated by Application Insights."
  value       = data.azapi_resource.application_insights.output.data_collection_rule_resource_id
}
