output "function_app_name" {
  description = "Name of the deployed Flex Consumption Function App."
  value       = module.functions.function_app_name
}

output "function_app_endpoint" {
  description = "Default hostname of the deployed Function App."
  value       = module.functions.function_app_endpoint
}

output "app_service_endpoint" {
  description = "Default hostname of the OpenTelemetry Collector App Service."
  value       = module.appservice.app_service_endpoint
}

output "event_hub_namespace_endpoint" {
  description = "Service Bus endpoint of the Event Hubs namespace."
  value       = module.eventhubs.service_bus_endpoint
}

output "managed_redis_resource_id" {
  description = "Resource ID of Azure Managed Redis."
  value       = module.redis.id
}

output "trace_ingestion_endpoint" {
  description = "Azure Monitor OTLP trace ingestion endpoint."
  value       = module.monitoring.trace_ingestion_endpoint
}

output "log_ingestion_endpoint" {
  description = "Azure Monitor OTLP log ingestion endpoint."
  value       = module.monitoring.log_ingestion_endpoint
}

output "metrics_ingestion_endpoint" {
  description = "Azure Monitor OTLP metrics ingestion endpoint."
  value       = module.monitoring.metrics_ingestion_endpoint
}

output "data_collection_rule_resource_id" {
  description = "Resource ID of the DCR generated by Application Insights."
  value       = module.monitoring.data_collection_rule_resource_id
}
